# Location of earnings call transcripts
TEST_DATA_DIR="../test_data"

# Tone Analyzer credentials
TONE_ANALYZER_APIKEY = '6dHOzaqYM6iSsdFPnJv38gHnOfmQH2SZ3EAXiHpeGj9O'
TWITTER_CONSUMER_API_KEY = 'HXdHnHHG0YBOxDlZQoS0oWdZG'
TWITTER_CONSUMER_SECRET_API_KEY= 'WIyQxcRnbFZwaA8QS5vAV0ArsiDoSp9JxE9QeX4e3BdRsQyHEB'
TWITTER_ACCESS_TOKEN='1190174804-QaZmW73Kmki6McEoAJmp9HUBFyM0ofNOOnzZjBW'
TWITTER_SECRET_ACCESS_TOKEN='TUmgdTjxczcyxEjb31FRKaiLMpTSIcFwWVdkiBUUa0EBm'

# NLU credentials
NLU_APIKEY = 'dRokypO8QXz9_CcUbx2z2lLm4WfMk8QgXHiQ3m0jDX11'
